services:
  web-prod:
    container_name: ${LZ}_phoenix_web_${ENV}
    image: ghcr.io/aleonard9/druthers-web:prod
    restart: unless-stopped
    env_file:
      - env/${ENV}.env
    networks:
      - local_network

networks:
  local_network:
    name: '${LZ}_network_${ENV}'
    external: true
